language: node_js
node_js:
  - 0.11.13
before_script:
  - npm install -g bower grunt grunt-cli
  - bower install
  - grunt debug
  - export NODEWEBKIT_BIN=/home/travis/build/TimotheeJeannin/StreamTim/cache/0.11.0/linux64/nw
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start